name: Test, build, push and deploy
on: push
env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_DOCKER_PKG: docker.pkg.github.com/${{ github.repository }}/pus-decorator
  IMAGE_GHCR: ghcr.io/${{ github.repository }}/pus-decorator
  PRINT_PAYLOAD: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Run maven tests
        run: mvn -B verify
  test-build-and-push:
    name: Test, build and push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build maven artifacts
        run: mvn -B package
      - name: Build Docker image
        run: docker build -t ${IMAGE_DOCKER_PKG} -t ${IMAGE_GHCR} .
      - name: Push to docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker tag ${IMAGE_DOCKER_PKG} ${IMAGE_DOCKER_PKG}:${IMAGE_TAG}
          docker push ${IMAGE_DOCKER_PKG}
      - name: Push to ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_REPOSITORY} --password-stdin
          docker tag ${IMAGE_GHCR} ${IMAGE_GHCR}:${IMAGE_TAG}
          docker push ${IMAGE_GHCR}